enable-magisk-update = true

# ReVanced Extended
[YouTube-Extended]
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.uptodown.com/android"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
included-patches = "'Visual preferences icons'"
excluded-patches = "'Custom Shorts action buttons' 'Custom branding icon for YouTube' 'Custom branding name for YouTube'"

[YT-Music-Extended]
app-name = "YT-Music"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.uptodown.com/android"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Hide player overlay filter'"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music'"

# ReVanced anddea
[YouTube-anddea]
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.uptodown.com/android"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced anddea"
build-mode = "both"

[YT-Music-anddea]
app-name = "YT-Music"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.uptodown.com/android"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced anddea"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Hide player overlay filter'"

# ReVanced
[YouTube]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.uptodown.com/android"
build-mode = "both"

[YT-Music]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.uptodown.com/android"
arch = "arm64-v8a"
build-mode = "both"
